services:
  webapi:
    build:
      context: ./demoapi2
    container_name: spring_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    networks:
      - data_api_network

  mysql_db:
    image: mysql:8.1.0
    restart: always
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=demoapidb
    volumes:
      - C:/data/mysql:/var/lib/mysql
    networks:
      - data_api_network

networks:
  data_api_network:
    external: true