services:
  mysqldb:
    image: mysql:latest
    restart: always
    container_name: "mysqldb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demoapidb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456789
#    volumes:
#      - C:/data/mysql:/var/lib/mysql
    networks:
      - bored-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost || exit 1" ]
      timeout: 20s
      retries: 10

  webapi:
    image: behnamghafouri/spring-oauth-server-image
    container_name: "springapi"
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/demoapidb?allowPublicKeyRetrieval=true"
      spring.datasource.user: apiuser
      spring.datasource.password: 123456
#      server.port: 8080
#      server.ssl.key-store=classpath: keystore.p12
#      server.ssl.key-store-password: 123456
#      server.ssl.key-store-type: PKCS12
#      server.ssl.key-alias: mykey

    networks:
      - bored-network

networks:
  bored-network:
    name: bored-network