services:
  mysql_db:
    image: mysql:8.1.0
    restart: always
    container_name: "mysql_db"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=demoapidb
#    volumes:
#      - C:/data/mysql:/var/lib/mysql
    networks:
      - data_api_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql_db_connector:
    image: mysql:8.1.0
    networks:
      - data_api_network
    depends_on:
      mysql_db:
        condition: service_healthy
    command: mysql -hmysql_db -uroot -p'123456'

  webapi:
    image: behnamghafouri/spring-oauth-server-image:latest
    container_name: "spring_api"
    depends_on:
      mysql_db:
      condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - data_api_network

networks:
  data_api_network:
    external: true