apiVersion: v1
kind: Service
metadata:
  name: mysql_db
spec:
  selector:
    app: mysql_db
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql_db
spec:
  selector:
    matchLabels:
      app: mysql_db
  template:
    metadata:
      labels:
        app: mysql_db
    spec:
      containers:
        - name: mysql_db
          image: mysql:8.1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 123456
            - name: MYSQL_DATABASE
              value: demoapidb