# Service
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    app: mysqldb
  ports:
    - port: 3306
      targetPort: 3306

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "toor"
            - name: MYSQL_DATABASE
              value: demoapidb
            - name: MYSQL_USER
              value: "apiuser"
            - name: MYSQL_PASSWORD
              value: "123456"