# Service
apiVersion: v1
kind: Service
metadata:
  name: springapi
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Update this if needed
    service.beta.kubernetes.io/azure-load-balancer-ssl-cert: "springapi-tls-secret"
    service.beta.kubernetes.io/azure-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: springapi
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapi
  template:
    metadata:
      labels:
        app: springapi
    spec:
      containers:
        - name: springapi
          image: behnamghafouri/spring-oauth-server-image
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.url
              value: "jdbc:mysql://mysqldb:3306/demoapidb?allowPublicKeyRetrieval=true"
            - name: spring.datasource.user
              value: "apiuser"
            - name: spring.datasource.password
              value: "123456"
          imagePullPolicy: Always
