# Service
apiVersion: v1
kind: Service
metadata:
  name: springapi
spec:
  selector:
    app: springapi
  ports:
    - port: 443
      targetPort: 443
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapi
  template:
    metadata:
      labels:
        app: springapi
    spec:
      containers:
        - name: springapi
          image: behnamghafouri/spring-oauth-server-image
          ports:
            - containerPort: 443
          env:
            - name: spring.datasource.url
              value: "jdbc:mysql://mysqldb:3306/demoapidb?allowPublicKeyRetrieval=true"
            - name: spring.datasource.user
              value: "apiuser"
            - name: spring.datasource.password
              value: "123456"
            - name: server.port
              value: "443"
            - name: server.ssl.key-store
              value: "keystore.p12"
            - name: server.ssl.key-store-password
              value: "123456"
            - name: server.ssl.key-store-type
              value: "PKCS12"
            - name: server.ssl.key-alias
              value: "mykey"
            - name: server.http.port
              value: "8080"
          imagePullPolicy: Always
