# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring_api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring_api
  template:
    metadata:
      labels:
        app: spring_api
    spec:
      containers:
        - name: spring_api
          image: behnamghafouri/spring-oauth-server-image
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
# Service
---
apiVersion: v1
kind: Service
metadata:
  name: spring_api
spec:
  selector:
    app: spring_api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer