name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file demoapi2/Dockerfile --tag behnamghafouri/spring-oauth-server-image

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image To Docker My Hub
      run: docker push behnamghafouri/spring-oauth-server-image

    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: setup service and deployment for mysql
      run: kubectl apply -f kube/mysql.yaml

    - name: setup service and deployment for java
      run: kubectl apply -f kube/spring_api.yaml